version: 2.1
executors:
  my-local-executor:
    docker:
      - image: circleci/python:3.11
    resource_class: rai-harshit/test-local-runners
jobs:
  build:
    executor: my-local-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            python -m unittest discover
  test:
    docker:
      - image: circleci/python:3.11  # Use the desired Python version
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
